# Generated by Django 5.2.7 on 2025-10-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_remove_product_order_orderdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'детали заказа', 'verbose_name_plural': 'детали заказа'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'заказы', 'verbose_name_plural': 'заказы'},
        ),
    ]
