# Generated by Django 5.2.7 on 2025-11-06 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_orderdetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
