# Generated by Django 5.2.7 on 2025-11-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_orderdetails_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Передан ресторану', 'Передан ресторану'), ('Готовится', 'Готовится'), ('Передан курьеру', 'Передан курьеру'), ('Готов', 'Готов')], default='Принят'),
        ),
    ]
