# Generated by Django 5.2.7 on 2025-11-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_remove_orderdetails_status_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Передан ресторану', 'Передан ресторану'), ('Готовится', 'Готовится'), ('Передан курьеру', 'Передан курьеру'), ('Отдан заказчику', 'Отдан заказчику')], default='Принят'),
        ),
    ]
