# Generated by Django 5.2.7 on 2025-11-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_orders_call_time_orders_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pay_method',
            field=models.CharField(choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], default='Наличностью'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='название'),
        ),
    ]
