# Generated by Django 5.2.8 on 2025-11-17 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_orders_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество продукта'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='call_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата звонка клиенту'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки клиенту'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pay_method',
            field=models.CharField(choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], default='Наличностью', verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан выполняюзий заказ'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Передан ресторану', 'Передан ресторану'), ('Готовится', 'Готовится'), ('Передан курьеру', 'Передан курьеру'), ('Отдан заказчику', 'Отдан заказчику')], default='Принят', verbose_name='Статус заказа'),
        ),
    ]
