# Generated by Django 5.2.8 on 2025-11-17 15:43

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_orderdetails_quantity_alter_orders_call_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='call_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата звонка клиенту'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата доставки клиенту'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pay_method',
            field=models.CharField(choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], db_index=True, default='Наличностью', verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='registration_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата регистрации заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Передан ресторану', 'Передан ресторану'), ('Готовится', 'Готовится'), ('Передан курьеру', 'Передан курьеру'), ('Отдан заказчику', 'Отдан заказчику')], db_index=True, default='Принят', verbose_name='Статус заказа'),
        ),
    ]
