# Generated by Django 5.2.8 on 2025-11-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_orders_call_time_alter_orders_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий к заказу'),
        ),
    ]
