# Generated by Django 5.2.8 on 2025-11-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_alter_orders_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pay_method',
            field=models.CharField(choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], db_index=True, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Не обработан', 'Не обработан'), ('Принят', 'Принят'), ('Передан ресторану', 'Передан ресторану'), ('Готовится', 'Готовится'), ('Передан курьеру', 'Передан курьеру'), ('Отдан заказчику', 'Отдан заказчику')], db_index=True, default='Не обработан', verbose_name='Статус заказа'),
        ),
    ]
