# Generated by Django 5.2.8 on 2025-12-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_alter_orders_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан выполняющий заказ'),
        ),
    ]
