# Generated by Django 5.2.7 on 2025-11-15 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Широта')),
                ('lan', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Долгота')),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 11, 15, 17, 2, 35, 597405, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
