# Generated by Django 5.2.7 on 2025-11-15 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopy_bd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geopy',
            old_name='lan',
            new_name='lon',
        ),
        migrations.AlterField(
            model_name='geopy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 17, 42, 9, 921736, tzinfo=datetime.timezone.utc)),
        ),
    ]
