# Generated by Django 5.2.7 on 2025-11-15 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopy_bd', '0002_rename_lan_geopy_lon_alter_geopy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 19, 39, 32, 807130, tzinfo=datetime.timezone.utc)),
        ),
    ]
