# Generated by Django 5.2.8 on 2025-11-17 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopy_bd', '0009_alter_geopy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 15, 54, 55, 124236, tzinfo=datetime.timezone.utc)),
        ),
    ]
