# Generated by Django 5.2.8 on 2025-11-19 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopy_bd', '0014_alter_geopy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopy',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки данных'),
        ),
    ]
